### ISSUE TITLE
在PHP 8.1.8下安装报错 php bin/hyperf.php mine:install 

### ISSUE THREAD

**Issue by auning** [kanyxmo/MineAdmin#26]
php: 8.1.8
OS: MacOS 12.2
尝试过的操作： composer update后依然报错
各项依赖的扩展都有，且composer install正常
` php bin/hyperf.php mine:install ` 报错
```
php bin/hyperf.php mine:install                                                                                                                     ✔  39s   16:32:43  
PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1646

Deprecated: Return type of Hyperf\Utils\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1646
PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1657

Deprecated: Return type of Hyperf\Utils\Collection::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1657
PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1668

Deprecated: Return type of Hyperf\Utils\Collection::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1668
PHP Deprecated:  Return type of Hyperf\Utils\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1682

Deprecated: Return type of Hyperf\Utils\Collection::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Collection.php on line 1682
PHP Deprecated:  Hyperf\AsyncQueue\Message implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/async-queue/src/Message.php on line 18

Deprecated: Hyperf\AsyncQueue\Message implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/async-queue/src/Message.php on line 18
PHP Deprecated:  Return type of Hyperf\Database\Model\Model::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1156

Deprecated: Return type of Hyperf\Database\Model\Model::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1156
PHP Deprecated:  Return type of Hyperf\Database\Model\Model::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1165

Deprecated: Return type of Hyperf\Database\Model\Model::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1165
PHP Deprecated:  Return type of Hyperf\Database\Model\Model::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1175

Deprecated: Return type of Hyperf\Database\Model\Model::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1175
PHP Deprecated:  Return type of Hyperf\Database\Model\Model::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1184

Deprecated: Return type of Hyperf\Database\Model\Model::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 1184
PHP Deprecated:  Return type of Hyperf\Database\Model\Model::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 850

Deprecated: Return type of Hyperf\Database\Model\Model::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/database/src/Model/Model.php on line 850
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 165

Deprecated: Return type of Hyperf\Utils\Fluent::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 165
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 175

Deprecated: Return type of Hyperf\Utils\Fluent::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 175
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 186

Deprecated: Return type of Hyperf\Utils\Fluent::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 186
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 196

Deprecated: Return type of Hyperf\Utils\Fluent::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 196
PHP Deprecated:  Return type of Hyperf\Utils\Fluent::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 143

Deprecated: Return type of Hyperf\Utils\Fluent::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Fluent.php on line 143
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 94

Deprecated: Return type of Hyperf\Utils\Optional::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 94
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 105

Deprecated: Return type of Hyperf\Utils\Optional::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 105
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 116

Deprecated: Return type of Hyperf\Utils\Optional::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 116
PHP Deprecated:  Return type of Hyperf\Utils\Optional::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 128

Deprecated: Return type of Hyperf\Utils\Optional::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Optional.php on line 128
PHP Deprecated:  Return type of Hyperf\Utils\Stringable::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Stringable.php on line 799

Deprecated: Return type of Hyperf\Utils\Stringable::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/utils/src/Stringable.php on line 799
PHP Deprecated:  Return type of Hyperf\Paginator\AbstractPaginator::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/paginator/src/AbstractPaginator.php on line 406

Deprecated: Return type of Hyperf\Paginator\AbstractPaginator::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/paginator/src/AbstractPaginator.php on line 406
PHP Deprecated:  Return type of Hyperf\Paginator\AbstractPaginator::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/paginator/src/AbstractPaginator.php on line 406

Deprecated: Return type of Hyperf\Paginator\AbstractPaginator::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/paginator/src/AbstractPaginator.php on line 406
[INFO] Swagger Url at 0.0.0.0:9501/swagger
PHP Fatal error:  Uncaught Hyperf\Di\Exception\InvalidDefinitionException: Entry "Mine\Command\UpdateProjectCommand" cannot be resolved: Parameter $name of __construct() has no value defined or guessable
Full definition:
Object[Mine\Command\UpdateProjectCommand] in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Exception/InvalidDefinitionException.php:20
Stack trace:
#0 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ObjectResolver.php(103): Hyperf\Di\Exception\InvalidDefinitionException::create(Object(Hyperf\Di\Definition\ObjectDefinition), 'Entry "Mine\\Com...')
#1 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ObjectResolver.php(66): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#2 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(62): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#3 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/DepthGuard.php(73): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#4 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(63): Hyperf\Di\Resolver\DepthGuard->call('Mine\\Command\\Up...', Object(Closure))
#5 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(194): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#6 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(82): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#7 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(127): Hyperf\Di\Container->make('Mine\\Command\\Up...')
#8 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/framework/src/ApplicationFactory.php(48): Hyperf\Di\Container->get('Mine\\Command\\Up...')
#9 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/FactoryResolver.php(56): Hyperf\Framework\ApplicationFactory->__invoke(Object(Hyperf\Di\Container))
#10 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(62): Hyperf\Di\Resolver\FactoryResolver->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#11 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/DepthGuard.php(73): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#12 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(63): Hyperf\Di\Resolver\DepthGuard->call('Hyperf\\Contract...', Object(Closure))
#13 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(194): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#14 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(82): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#15 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(127): Hyperf\Di\Container->make('Hyperf\\Contract...')
#16 /Applications/MxSrvs/www/cloudcpadmin/bin/hyperf.php(27): Hyperf\Di\Container->get('Hyperf\\Contract...')
#17 /Applications/MxSrvs/www/cloudcpadmin/bin/hyperf.php(29): {closure}()
#18 {main}
  thrown in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Exception/InvalidDefinitionException.php on line 20

Fatal error: Uncaught Hyperf\Di\Exception\InvalidDefinitionException: Entry "Mine\Command\UpdateProjectCommand" cannot be resolved: Parameter $name of __construct() has no value defined or guessable
Full definition:
Object[Mine\Command\UpdateProjectCommand] in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Exception/InvalidDefinitionException.php:20
Stack trace:
#0 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ObjectResolver.php(103): Hyperf\Di\Exception\InvalidDefinitionException::create(Object(Hyperf\Di\Definition\ObjectDefinition), 'Entry "Mine\\Com...')
#1 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ObjectResolver.php(66): Hyperf\Di\Resolver\ObjectResolver->createInstance(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#2 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(62): Hyperf\Di\Resolver\ObjectResolver->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#3 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/DepthGuard.php(73): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#4 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(63): Hyperf\Di\Resolver\DepthGuard->call('Mine\\Command\\Up...', Object(Closure))
#5 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(194): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#6 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(82): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\ObjectDefinition), Array)
#7 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(127): Hyperf\Di\Container->make('Mine\\Command\\Up...')
#8 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/framework/src/ApplicationFactory.php(48): Hyperf\Di\Container->get('Mine\\Command\\Up...')
#9 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/FactoryResolver.php(56): Hyperf\Framework\ApplicationFactory->__invoke(Object(Hyperf\Di\Container))
#10 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(62): Hyperf\Di\Resolver\FactoryResolver->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#11 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/DepthGuard.php(73): Hyperf\Di\Resolver\ResolverDispatcher->Hyperf\Di\Resolver\{closure}()
#12 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Resolver/ResolverDispatcher.php(63): Hyperf\Di\Resolver\DepthGuard->call('Hyperf\\Contract...', Object(Closure))
#13 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(194): Hyperf\Di\Resolver\ResolverDispatcher->resolve(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#14 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(82): Hyperf\Di\Container->resolveDefinition(Object(Hyperf\Di\Definition\FactoryDefinition), Array)
#15 /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Container.php(127): Hyperf\Di\Container->make('Hyperf\\Contract...')
#16 /Applications/MxSrvs/www/cloudcpadmin/bin/hyperf.php(27): Hyperf\Di\Container->get('Hyperf\\Contract...')
#17 /Applications/MxSrvs/www/cloudcpadmin/bin/hyperf.php(29): {closure}()
#18 {main}
  thrown in /Applications/MxSrvs/www/cloudcpadmin/vendor/hyperf/di/src/Exception/InvalidDefinitionException.php on line 20


```

**Comment by kanyxmo** [comment]
还不支持8.1哦，用8.0版本
