### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by caicaispace** [kanyxmo/MineAdmin#3]
```
[ERROR] Error while decoding from Base64Url, invalid base64 characters detected
[ERROR] /home/shipin520/dev/project/admin/MineAdmin/vendor/lcobucci/jwt/src/Encoding/CannotDecodeContent.php
string(3184) "#0 /home/shipin520/dev/project/admin/MineAdmin/vendor/lcobucci/jwt/src/SodiumBase64Polyfill.php(66): Lcobucci\JWT\Encoding\CannotDecodeContent::invalidBase64String()
#1 /home/shipin520/dev/project/admin/MineAdmin/vendor/lcobucci/jwt/src/Signer/Key/InMemory.php(39): Lcobucci\JWT\SodiumBase64Polyfill::base642bin('abcdefg', 1)
#2 /home/shipin520/dev/project/admin/MineAdmin/vendor/xmo/jwt-auth/src/JWT.php(202): Lcobucci\JWT\Signer\Key\InMemory::base64Encoded('abcdefg')
#3 /home/shipin520/dev/project/admin/MineAdmin/vendor/xmo/jwt-auth/src/JWT.php(64): Xmo\JWTAuth\JWT->getKey(Array)
#4 /home/shipin520/dev/project/admin/MineAdmin/mine/Helper/LoginUser.php(156): Xmo\JWTAuth\JWT->getToken(Array)
#5 /home/shipin520/dev/project/admin/MineAdmin/runtime/container/proxy/App_System_Service_SystemUserService.proxy.php(142): Mine\Helper\LoginUser->getToken(Array)
#6 /home/shipin520/dev/project/admin/MineAdmin/runtime/container/proxy/App_System_Controller_LoginController.proxy.php(58): App\System\Service\SystemUserService->login(Array)
#7 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/http-server/src/CoreMiddleware.php(161): App\System\Controller\LoginController->login(Object(App\System\Request\User\SystemUserLoginRequest))
#8 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/http-server/src/CoreMiddleware.php(113): Hyperf\HttpServer\CoreMiddleware->handleFound(Object(Hyperf\HttpServer\Router\Dispatched), Object(Hyperf\HttpMessage\Server\Request))
#9 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\HttpServer\CoreMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#10 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#11 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/validation/src/Middleware/ValidationMiddleware.php(83): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#12 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Validation\Middleware\ValidationMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#13 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#14 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#15 /home/shipin520/dev/project/admin/MineAdmin/vendor/hyperf/http-server/src/Server.php(117): Hyperf\Dispatcher\HttpDispatcher->dispatch(Object(Hyperf\HttpMessage\Server\Request), Array, Object(Mine\Middlewares\HttpCoreMiddleware))
#16 /home/shipin520/dev/project/admin/MineAdmin/mine/MineServer.php(25): Hyperf\HttpServer\Server->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#17 {main}"
```

**Comment by kanyxmo** [comment]
php bin/hyperf.php mine:gen-jwt --jwtSecret=JWT_API_SECRET
执行这个命令再试试，可以加群：15169734

**Comment by littlezo** [comment]
执行命令后重启重新加载环境变量文件

**Comment by caicaispace** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by qibinghua** [comment]
php bin/hyperf.php mine:jwt-gen --jwtSecret=JWT_API_SECRET
php bin/hyperf.php mine:jwt-gen --jwtSecret=JWT_SECRET

这两个key必须是base64的
